name: 'rocm-toolkit-dev'
description: 'Installs Rocm Toolkit and adds it to PATH'
author: '@DevelVitorF'
inputs:
  rocm:
    description: 'Rocm version'
    required: false
    default: '5.5.1'
  sub-packages:
    description: 'Only installs specified subpackages, must be in the form of a JSON array.'
    required: false
    default: '[]'
  non-rocm-sub-packages:
    description:
      'Only installs specified subpackages that do not have the rocm prefix,
      must be in the form of a JSON array.'
    required: false
    default: '[]'
  method:
    description: "Installation method: 'local' or 'network'."
    required: false
    default: 'local'
  use-github-cache:
    description: 'Use GitHub cache to cache downloaded installer on GitHub servers'
    required: false
    default: 'true'
  use-local-cache:
    description: 'Use local cache to cache downloaded installer on the local runner'
    required: false
    default: 'true'
  log-file-suffix:
    description: 'Suffix of log file name in artifact'
    required: false
    default: 'log.txt'
outputs:
  ROCM_PATH:
    description: 'Path to Rocm installation'
  HIP_PATH:
    description: 'Path to HIP SDK installation'
  rocm:
    description: 'Version of Rocm installed'
runs:
  using: 'node24'
  main: dist/index.js
branding:
  icon: box
  color: green
