allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - prettier@3.9.9
  - ts-jest@29.4.13
